### ISSUE TITLE
Packaged Problems

### ISSUE THREAD

**Issue by JaxkDev** [jackthehack21/NodeLife#1]
**Details:**
When packaging using pyinstaller, extra data such as .txt .dat will not be saved to the bundled app.

**To Reproduce**
1. pyinstaller start.spec

**Expected behavior**
A fully functional executable

**Desktop (please complete the following information):**
 - Linux
 - Windows

**Smartphone (please complete the following information):**
 - iPhone 6 (Private use)

**Comment by jackthehack21** [comment]
Tried datas variable to copy resources still no luck, next step use one dir to debug what gets added.

**Comment by jackthehack21** [comment]
one dir with datas works but not --onefile, ive decided to change the program so all resources will be downloaded instead of compiled.
